version: 0.2


phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login  --no-include-email --region us-east-1)
      - REPOSITORY_URI=860061945305.dkr.ecr.us-east-1.amazonaws.com/005policy-ecrrepo
      - Password=
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - mvn --file authorization/pom.xml clean install -DskipTests
      - echo Building the Docker image...
      - docker login --username maverick6798 --password $Password
      - docker build -f authorization/Dockerfile -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"005auth-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > authorization/imagedefinitions.json
      - cat authorization/imagedefinitions.json
      - ls
      - pwd
artifacts:
  files:
   - authorization/imagedefinitions.json





